<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\DataAccess.Abstractions\DataAccess.Abstractions.csproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.SQLite\DataAccess.SQLite.csproj" />
    <ProjectReference Include="..\DomainModels\DomainModels.csproj" />
    <ProjectReference Include="..\Shared\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\Shared\Utils\Utils.csproj" />
  </ItemGroup>

</Project>
