// <auto-generated />
using System;
using DataAccess.SQLite.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.SQLite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531153534_ModifyReciepts2")]
    partial class ModifyReciepts2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DomainModels.Domains.DomainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("DomainModels.Domains.RentedDomainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndOfRenting")
                        .HasColumnType("TEXT")
                        .HasColumnName("to");

                    b.Property<DateOnly>("StartOfRenting")
                        .HasColumnType("TEXT")
                        .HasColumnName("from");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .IsUnique();

                    b.ToTable("RentedDomains");
                });

            modelBuilder.Entity("DomainModels.Receipts.ReceiptModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndOfRenting")
                        .HasColumnType("TEXT")
                        .HasColumnName("to");

                    b.Property<int>("INN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartOfRenting")
                        .HasColumnType("TEXT")
                        .HasColumnName("from");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("DomainModels.Domains.RentedDomainModel", b =>
                {
                    b.HasOne("DomainModels.Domains.DomainModel", "Domain")
                        .WithOne("RentedDomain")
                        .HasForeignKey("DomainModels.Domains.RentedDomainModel", "DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DomainModels.Domains.DomainModel", b =>
                {
                    b.Navigation("RentedDomain")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
