// <auto-generated />
using System;
using DataAccess.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.SQLite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DomainModels.Domains.DomainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("DomainModels.Domains.RentedDomainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndOfRenting")
                        .HasColumnType("TEXT")
                        .HasColumnName("to");

                    b.Property<DateOnly>("StartOfRenting")
                        .HasColumnType("TEXT")
                        .HasColumnName("from");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .IsUnique();

                    b.ToTable("RentedDomains");
                });

            modelBuilder.Entity("DomainModels.Domains.RentedDomainModel", b =>
                {
                    b.HasOne("DomainModels.Domains.DomainModel", "Domain")
                        .WithOne("RentedDomain")
                        .HasForeignKey("DomainModels.Domains.RentedDomainModel", "DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DomainModels.Domains.DomainModel", b =>
                {
                    b.Navigation("RentedDomain")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
